import type { Metadata } from "next"
import { galmuri } from "@/utils/fonts"
import "./globals.css"
import { getServerSession } from "next-auth"
import { authOptions } from "./api/auth/[...nextauth]/auth"
import ToastContainer from "./components/ToastContainer"
import DialogContainer from "./components/DialogContainer"
import NextAuthSessionProviders from "./providers/NextAuthSessionProviders"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className={`${galmuri.className} antialiased`}>
        <NextAuthSessionProviders session={session}>
          {children}
          <ToastContainer />
          <DialogContainer />
        </NextAuthSessionProviders>
      </body>
    </html>
  )
}
