import type { Metadata } from "next"
import { galmuri } from "@/utils/fonts"
import "./globals.css"
import { getServerSession } from "next-auth"
import { authOptions } from "./api/auth/[...nextauth]/auth"
import ToastContainer from "./components/ToastContainer"
import DialogContainer from "./components/DialogContainer"
import NextAuthSessionProviders from "./providers/NextAuthSessionProviders"
import ReactQueryProvider from "./providers/ReactQueryProvider"
import ConditionHeader from "./components/ConditionHeader"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className={`${galmuri.className} flex justify-center antialiased`}>
        <div
          className={`relative box-border flex min-h-screen w-full max-w-[430px] flex-col items-center !bg-[var(--color-white-200)] px-[30px] pt-[100px]`}
        >
          <ConditionHeader />
          <NextAuthSessionProviders session={session}>
            <ReactQueryProvider>{children}</ReactQueryProvider>
            <ToastContainer />
            <DialogContainer />
          </NextAuthSessionProviders>
        </div>
      </body>
    </html>
  )
}
