import type { Metadata } from "next"
import { galmuri } from "@/utils/fonts"
import "./globals.css"
import Providers from "./providers"
import DialogContainer from "./components/DialogContainer"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${galmuri.className} antialiased`}>
        <Providers>
          {children}
          <DialogContainer />
        </Providers>
      </body>
    </html>
  )
}
